### ISSUE TITLE
Distorted window decorations with fractional scaling

### ISSUE THREAD

**Issue by lucidtanooki** [doncsugar/willow-theme#3]
Hi @doncsugar - great theme!

Wanted to let you know that on HiDPI with fractional scaling the window decorations don't look like intended:

![willow_hidpi](https://user-images.githubusercontent.com/79907590/136387977-a25b11ee-16e5-49ad-88ed-aafe8683ecc2.png)

Best regards

**Comment by doncsugar** [comment]
Hello,

Thanks!

This is a bug with Aurorae themes. Have you tried using Wayland?

Also, I noticed that you were using normal borders. Were you aware that the recommended settings are "No side borders" ?

**Comment by lucidtanooki** [comment]
I tried "no borders" - did not help. Did not try wayland, as I want to use the NVidia drivers. But I can try. If it's a bug in aurora, why does it work in the breeze theme?

Best Regards.

**Comment by doncsugar** [comment]
I just wanted to know since its difficult to tell users what the settings should be because it has to be manually configured. "No side borders" gets rid of the opaque edges near the bottom. Of course, that's only if you are using Lightly with opaque window colors.

This might be able to help: https://blog.davidedmundson.co.uk/blog/running-kwin-wayland-on-nvidia/

Aurorae is actually a different window decoration than Breeze. Instead of pure code, Aurorae takes SVGs and uses them to draw the borders. If you know how to use Inkscape and little bit about how Aurorae works, you can actually make your own.

If you would like to do some experimenting, I think your issue can be resolved if you change the padding in the theme. Go to `/.local/share/aurorae/themes/` and into the one you're using. The text file that ends in "rc" is what you want.

Change these 4 lines:

PaddingTop=32
PaddingBottom=76
PaddingRight=47
PaddingLeft=47

To these values:

PaddingTop=24
PaddingBottom=56
PaddingRight=35
PaddingLeft=35

Save it and close and reopen system settings. Change your window decoration theme to another and then back. You can increase or decrease the values to get it just right. These values might be a bit closer to the right size.

**Comment by lucidtanooki** [comment]
I'll try that. Thanks.
