### ISSUE TITLE
Tasks.svgz

### ISSUE THREAD

**Issue by yehonatan2020** [doncsugar/willow-theme#5]
First of all, I must say, what a really nice job done with this. The size of the icons on plasma task manager are much better. Only one thing that seems a bit weird is when you click say the volume icon, there is a like an overlay that appears, but the sizing is not correct; it's too small, and so the icons overlap it. Would be maybe nicer to see a blue line underneath the icons instead of this one

**Comment by yehonatan2020** [comment]
![tasks](https://user-images.githubusercontent.com/65138695/177329757-b569d423-0d2a-4078-83e8-a04f63f7df5b.png)

**Comment by doncsugar** [comment]
Thanks for the feedback, glad to know things are better!

I presume you are using Latte Dock?

Unfortunately, there's nothing I can do about it. For some reason Latte draws tasks.svg and tabbar.svg over the system tray. Because Willow's tasks.svg is a hack, it will always look stretched. @vinceliuice's Fluent theme is the correct way to do it.

You can try:

Replacing that Latte panel with the standard Plasma panel should fix it:

![image](https://user-images.githubusercontent.com/46570709/177661333-f07bc412-367d-48d2-b46b-53becf18a9a9.png)

Alternatively, @psifidotos recommends using plasma-systray-latte-tweaks instead of the stock system tray: https://github.com/psifidotos/plasma-systray-latte-tweaks
The bug is here: https://bugs.kde.org/show_bug.cgi?id=455925

**Comment by yehonatan2020** [comment]
Thanks for that. You are right, the issue is to do with Latte dock. I switched to using the panel and its all perfect!
